version: "3.8"
services:
  redis:
    image: redis:6.0-alpine
    expose:
      - "6379"

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file: .db.env
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:1.19.5-alpine
    environment:
      VIRTUAL_HOST: testing.local
    restart: "no"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public
      - ./storage:/app/storage

  php:
    build:
      target: dev
    restart: "no"
    depends_on:
      - composer
      - redis
      - db
    volumes:
      - ./:/app:rw
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  node:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run watch"

  composer:
    image: composer:2.0.8
    working_dir: /app
    #environment:
    #  SSH_AUTH_SOCK: /ssh-auth.sock
    volumes:
      - ./:/app
    #  - "$SSH_AUTH_SOCK:/ssh-auth.sock"
    #  - /etc/passwd:/etc/passwd:ro
    #  - /etc/group:/etc/group:ro
    command: composer install --ignore-platform-reqs --no-scripts

volumes:
  db-data: